version: '3.1'
services:
  testing:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      elasticsearch:
        condition: service_healthy
      extension:
        condition: service_started
    volumes:
      - type: volume
        source: cache
        target: /var/data
    links:
      - elasticsearch
  extension:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - "GO_BUILDER=ghcr.io/linuxsuren/library/golang:1.22"
        - "BASE_IMAGE=ghcr.io/linuxsuren/library/alpine:3.12"
        - GOPROXY=${GOPROXY}

  elasticsearch:
    image: ghcr.io/linuxsuren/library/elasticsearch:8.17.4
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=root
    healthcheck:
      test: ["CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/9200"]
      interval: 3s
      timeout: 30s
      retries: 10
    ports:
      - 9200
volumes:
  cache:
